# Generated by Django 4.0.4 on 2022-06-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_publicacion_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='image',
        ),
    ]
