# Generated by Django 4.0.4 on 2022-06-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_alter_categoria_options_rename_image_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='image',
        ),
    ]
