# Generated by Django 4.0.4 on 2022-06-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_rename_imagen_producto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
    ]
